"""create user preferences

Revision ID: 9c092fa09209
Revises: 04522d6d6854
Create Date: 2026-10-03 06:33:35.710503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c092fa09209'
down_revision: Union[str, Sequence[str], None] = '04522d6d6854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('time_zone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('sleep_start', sa.Time(), nullable=True),
    sa.Column('sleep_end', sa.Time(), nullable=True),
    sa.Column('reduced_motion', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )

    op.create_foreign_key(
        "user_preferences_user_id_fkey",
        "user_preferences",
        "users",
        ["user_id"],
        ["id"],
        source_schema="public",
        referent_schema="auth",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "user_preferences_user_id_fkey",
        "user_preferences",
        schema="public",
        type_="foreignkey",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
